from tkinter import *

root = Tk()
l1 = Label(root, text="Username")
l2 = Label(root, text="Mobile")
l3 = Label(root, text="Email")
l4 = Label(root, text="Age")
l5 = Label(root, text="Password1")
l6 = Label(root, text="Password2")

e1 = Entry(root)
e2 = Entry(root)
e3 = Entry(root)
e4 = Entry(root)
e5= Entry(root)
e6 = Entry(root)
but1 =Button(root,text="login")
but2=Button(root,text='cancel')

l1.grid(row=0, column=0)
e1.grid(row=0, column=1)
l2.grid(row=1, column=0)
e2.grid(row=1, column=1)
l3.grid(row=2, column=0)
e3.grid(row=2,column=1)
l4.grid(row=3,column=0)
e4.grid(row=3,column=1)
l5.grid(row=4,column=0)
e5.grid(row=4,column=1)
l6.grid(row=5,column=0)
e6.grid(row=5,column=1)
but1.grid(row=6,column=0)
but2.grid(row=6,column=1)
root.mainloop()